### ISSUE TITLE
Only 1 table supported per page

### ISSUE THREAD

**Issue by Netflux** [ngPigeon/pigeon-table#2]
When adding multiple tables to the same page, only 1 of them is functional (the last to be stored in the **$_SESSION**). Using **$_SESSION** to store the table information the way it is now limits it to a single entry.

If you want to support multiple tables, it would be best to send the table name from the client-side (or grab it from the SQL query as done in the **SELECT** section) rather than relying on it being set in the session.

**Comment by alvinvoonyn** [comment]
We are trying to solve this issue.
Thank you for your feedback. ^^

**Comment by alvinvoonyn** [comment]
Solved in v1.1
https://github.com/alvinvoonyn/pigeon-table/releases/tag/v1.0.1
