### ISSUE TITLE
"Group by" and "Join" keywords being upper case sensitive

### ISSUE THREAD

**Issue by xLesterGG** [ngPigeon/pigeon-table#3]
As we are writing SQL statements here, the behavior of statements here should follow the same behavior of normal SQL where it is not case sensitive.

**Comment by alvinvoonyn** [comment]
We'll fix this bug.
Thank you for your feedback. ^^

**Comment by alvinvoonyn** [comment]
Solved in v1.0.1
https://github.com/alvinvoonyn/pigeon-table/releases/tag/v1.0.1
